//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuis2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class buku
    {
        public int Id { get; set; }
        public string judul { get; set; }
        public string penulis { get; set; }
        public string tahun_terbit { get; set; }
        public string kategori { get; set; }
    }
}
